### ISSUE TITLE
Chart instance methods missing: showLoading and hideLoading

### ISSUE THREAD

**Issue by Abin-Liu** [blazor-cn/Blazor.ECharts#18]
创建的Echarts实例目前缺少showLoading()和hideLoading()这两个成员方法，虽然谈不上必需，但如果有的话，在加载大量数据等待较长时间时能显著提高用户体验。希望可以添加。

**Comment by lishewen** [comment]
https://github.com/blazor-cn/Blazor.ECharts/blob/02fac16b9eaf2a2facc57361f5d2f1325bbf6a73/Blazor.ECharts/wwwroot/core.js#L25

默认是使用了showLoading了的，不需要显式调用，如果有更好的方案欢迎PR:)

**Comment by Abin-Liu** [comment]
希望可以手动调用，因为实际使用中我们一般是请求数据前就要让chart显示loading界面了，而不是在渲染chart前，具体时间线一般如下：

1. chart.showLoading()
2. 发送ajax请求
3. 等待远程数据
4. 预处理数据，生成option
5. chart.SetOptionAsync(option)
6. chart.hideLoading()

所以loading主要是用来填充远程数据请求过程的，也是耗时最长的过程。

**Comment by Abin-Liu** [comment]
已PR

**Comment by lishewen** [comment]
感谢，已发布版本
