### ISSUE TITLE
关于回调函数序列化

### ISSUE THREAD

**Issue by Ponderfly** [blazor-cn/Blazor.ECharts#2]
有部分选项接收的是回调函数，比如legend. formatter  可以接收
formatter: function (name) {
    return 'Legend ' + name;
}
如果直接传字符串序列化出来不对，有没有什么办法设置呢

**Comment by lishewen** [comment]
带function的不是标准的json，目前system.text.json是无法处理的。

Newtonsoft.json倒是可以通过ToRaw来直接传字符串进去实现，可以让你老项目的实现

目前控件中也留有OptionRaw属性通过传原文来应对这样的需求，可参考Demo中的index.razor

对于function这边的建议是能通过.net方法预处理的应该优先选择.net预处理，如Demo中WordCloud.razor的随机颜色方法。
不能的可先填个占位符，把option对象序列化为string后再替换占位符插入function后传进OptionRaw中

未来的迭代中我看看能不能通过特性来实现一部到位的Option配置

**Comment by lishewen** [comment]
已通过.net 6 preview 7的Libraries: “write raw” JSON with System.Text.Json.Utf8JsonWriter（ https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-7/#libraries-write-raw-json-with-system-text-json-utf8jsonwriter ）新特性解决此问题，项目需跟着升级.net 6 preview 7

传递一个JFunc，到属性处即可new JFunc(){RAW="function (idx) {return idx * 10;}"}

详情可查看net6分支下的Demo /bar/bar2
