### ISSUE TITLE
关于dispatchAction功能

### ISSUE THREAD

**Issue by andrewlei77** [blazor-cn/Blazor.ECharts#20]
请问dispatchAction功能如何实现？能给个例子吗？
ECharts自带的例子里是这样写的： myChart.dispatchAction({...
但是在Blazor里没有myChart这样的变量。所以我不知道该怎么调用dispatchAction。

**Comment by lishewen** [comment]
https://github.com/blazor-cn/Blazor.ECharts/blob/1732929608336d3f08fa91e8a12534838081407a/Blazor.ECharts.Demo/Pages/Pie/Pie2.razor.cs#LL74C9-L74C9

已增加，看这个例子
