### ISSUE TITLE
tooltip回调函数

### ISSUE THREAD

**Issue by andrewlei77** [blazor-cn/Blazor.ECharts#23]
tooltip中有个新增的回调函数valueFormatter。我按照网上例子这样写：ValueFormatter = "(value) => value.toFixed(2)" ，
在tooltip.cs中增加了        public string ValueFormatter { set; get; }
但是没有作用。tooltip不能显示了。
请您看看如何解决？谢谢

**Comment by lishewen** [comment]
在json描述中需要传递js函数的，可使用JFunc定义，可参考这个例子：
https://github.com/blazor-cn/Blazor.ECharts/blob/bb1eb7d7d1ad11e8541568b783add085769ededa/Blazor.ECharts.Demo/Pages/Timeline/AreaTimeAxis.razor.cs#L32
