### ISSUE TITLE
当使用EChartsOptions<T>配置图表的时候，Theme="dark"无效

### ISSUE THREAD

**Issue by Dolphinsimon** [blazor-cn/Blazor.ECharts#4]
当使用EChartsOptions<T>配置图表的时候，深色模式的配置不起作用，使用OptionRaw不受影响。

重现步骤：
使用默认的Demo工程，打开后不作任何修改，启动工程，切换到/bar/bar3页面，深色模式正常；
在当前页面直接刷新浏览器，页面重新加载后，深色模式无效。

这个问题是我们在一个首页放置图表的工程发现，如果首页就使用EChartsOptions<T>，那么无论如何，深色模式都不会生效。

总结下来就是当使用EChartsOptions<T>配置图表，且当前页面是加载的第一个页面时，深色模式无效；
或EChartsOptions<T>配置图表，当前页面不是第一个页面，但是刷新后深色模式无效。

**Comment by lishewen** [comment]
已更新

**Comment by Dolphinsimon** [comment]
谢谢，新版已经解决
