### ISSUE TITLE
用于 .Net 5 winform

### ISSUE THREAD

**Issue by FreeVB** [blazor-cn/Blazor.ECharts#5]
你好，请问这个能在 .Net 5.0 以上的WinForm 中使用吗？

**Comment by kobeliu9527** [comment]
加油，大佬，就指望你了，幸苦幸苦

**Comment by AZhrZho** [comment]
我正在开发一个新的基于Webview2的封装，可用于winform/wpf：https://github.com/AZhrZho/ECharts.Net
欢迎尝试和交流。
