### ISSUE TITLE
event添加失败

### ISSUE THREAD

**Issue by Henxun** [blazor-cn/Blazor.ECharts#6]
![image](https://user-images.githubusercontent.com/38826162/142967314-680ed98e-5dff-4a5e-aab8-21e31b2cebb8.png)
![image](https://user-images.githubusercontent.com/38826162/142967389-eee31416-ee41-4e48-a1df-f5d00a016721.png)

我遇到的问题：
![image](https://user-images.githubusercontent.com/38826162/142967477-4aaa267f-4ca3-4434-95f3-865226a326ff.png)

**Comment by lishewen** [comment]
https://github.com/blazor-cn/Blazor.ECharts/blob/master/Blazor.ECharts.Demo/Pages/Bar/Bar1.razor

**Comment by Henxun** [comment]
![image](https://user-images.githubusercontent.com/38826162/143154084-0a24ed1d-2305-4c2a-961c-640cd7742ff1.png)
是异步的问题

**Comment by Henxun** [comment]
👍,谢谢
