### ISSUE TITLE
Support chart resizes

### ISSUE THREAD

**Issue by jazzmanro** [blazor-cn/Blazor.ECharts#7]
Hello, thanks for your efforts.
I need to resize charts (e.g. browser window resizes). I noticed that ECharts supports that via the .resize() function but I can't see a way to invoke that via this project. The ComponentBase.Refresh() doesn't do the trick.
Any plans to support this? Ideally this would be nice to work out of the box by handling it in JS maybe so that we actually don't care although manual invocation may be needed for other workflows though.

**Comment by lishewen** [comment]
Resize is already supported in version 0.7.2

**Comment by jazzmanro** [comment]
Thanks! However I see a few issues:
- I think a debounce function should be used to limit number of resize events. In my case, when I resize the browser in the console I get something like `20​ 窗口触发ReSize事件` (BTW, maybe you should remove this log?)
- `Error: Could not find 'echartsFunctions.RemoveResizeListener' ('RemoveResizeListener' was undefined).` - that's an easy one, in JS I see it is `removeResizeListener`

**Comment by lishewen** [comment]
Fixed in version 0.7.5

**Comment by jazzmanro** [comment]
Thank you, looks good now, it is very good that resize is also controllable manually.
